### ISSUE TITLE
What is the token or user?

### ISSUE THREAD

**Issue by SergiosCode** [deltarod/Discord-PUG-bot#2]

**Comment by deltarod** [comment]
On startup, you will supply the token for your bot account [(created here)](https://discordapp.com/login?redirect_to=%2Fdevelopers%2Fapplications%2Fl). Then, you will supply your user ID in discord to force yourself to have 100% of commands regardless of server. Currently the bot itself is broken and will not log in, I will need to rework that and expect that with a week or two.

**Comment by SergiosCode** [comment]
oh okay. Let me know when its up. Thank you!!

**Comment by SergiosCode** [comment]
Is the bot up and running?

**Comment by deltarod** [comment]
Not as of yet, I had finals this week so I haven't had the time. I'll take a look at it right now and see what I can do!

**Comment by SergiosCode** [comment]
Thanks! You're the best!

**Comment by deltarod** [comment]
Hi, I have gone and updated the bot. If you need help setting up the bot, check out [the wiki!](https://github.com/deltarod/Discord-PUG-bot/wiki/Installing)

**Comment by SergiosCode** [comment]
okay thank you
